#!/bin/sh
# vim: set syn=sh et ai sw=2 st=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd "$(dirname "$0")"
[ "$(basename "$(pwd)")" = "scripts" ] && cd ..

. scripts/00_common
. scripts/03_readmodules
echo3 "Checking modules"
kmodule=''
lastmodule=''
if [ -z "$kmodule" ]; then
  while read m; do
    list="$(echo "$m"|cut -d\| -f3-)"
    m=$(echo "$m"|cut -d\| -f1-2|sed 's/|/-/')
    echo3 "Verifying packages for $m..."
    lastmodule=$m
    for p in $list; do
      if [ $p = $KERNELPKGNAME ]; then
        # module where the kernel live is
        kmodule=$m
      fi
      file="$(find -L "$startdir"/PKGS -name "$p-*"|grep "$p-[^-]\+-[^-]\+-[^-]\+.t[gblx]z"|head -n 1)"
      if [ ! -e "$file" ]; then
        quit "$p, referenced by module $m, is not available in $startdir/PKGS/"
        exit 1
      fi
    done
  done < "$modules"
fi
export kmodule
export lastmodule
