#!/bin/sh
# vim: set syn=sh ft=sh et sw=2 sts=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ "$(basename $(pwd))" = scripts ] && cd ..

. scripts/00_common
echo3 "Creating ISO..."
cd "$startdir"/src
CDNAME="${DISTRO}Live_${VER}"
echo $CDNAME
[ -n "$DEBUG" ] && DEBUG='-d 1' || DEBUG='-d 0'
background_flag=''
background_val=''
if [ -n "$THEME" ] && [ -d "$startdir"/themes/$THEME ]; then
  background_flag='-t'
  background_val="$startdir"/themes/$THEME
elif [ -z "$BGIMAGE_NAME" ]; then
  background_flag='-i'
  background_val="$startdir"/$BGIMAGE_NAME
fi
./salt/create-iso.sh $background_flag $background_val -k "$startdir/PKGS/$KERNELPKGNAME"-*-*-*.txz $DEBUG -v "$CDNAME" -o "$startdir/$ISO_NAME"
cd "$startdir"
md5sum "$ISO_NAME" > "$ISO_NAME.md5"
