#!/bin/sh
# vim: set syn=sh et ai sw=2 st=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd "$(dirname "$0")"
[ "$(basename "$(pwd)")" = "scripts" ] && cd ..

. scripts/00_common
echo3 "Creating ISO..."
cd "$startdir"/src
find salt/overlay -name '.svn' -type d -prune -exec rm -rf '{}' \;
CDNAME="${DISTRO}Live_${VER}"
echo $CDNAME
[ -n "$DEBUG" ] && DEBUG='-d 1' || DEBUG='-d 0'
./salt/create-iso.sh -g -i "$startdir/$BGIMAGE_NAME" -k "$startdir/PKGS/$KERNELPKGNAME"-*-*-*.txz $DEBUG -v "$CDNAME" -o "$startdir/$ISO_NAME"
cd "$startdir"
md5sum "$ISO_NAME" > "$ISO_NAME.md5"
