#!/bin/sh
# vim: set syn=sh et ai sw=2 st=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ $(basename $(pwd)) = scripts ] && cd ..

. scripts/00_common
echo3 "Creating extra initrd..."
cd "$startdir"/src
find salt/overlay -name '.svn' -type d -prune -exec rm -rf '{}' \;
INITRDNAME="initextra-$VER${RLZ:+-$RLZ}.$COMP"
echo $INITRDNAME
./salt/extra/create-initextra.sh $COMP $DEBUG
mv salt/extra/initextra.$COMP "$startdir"/$INITRDNAME
cd "$startdir"
md5sum "$INITRDNAME" > "$INITRDNAME.md5"
