#!/bin/sh
# vim: set syn=sh ft=sh et sw=2 sts=2 ts=2 tw=0:
# Maintainer: JRD <jrd@salixos.org>
# Contributors: Shador <shador@salixos.org>, Akuna <akuna@salixos.org>
# Licence: GPL v3+
#
cd $(dirname "$0")
[ "$(basename $(pwd))" = scripts ] && cd ..

. scripts/00_common
echo3 "Creating extra initrd..."
cd "$startdir"/src
INITRDNAME="initextra-$VER${RLZ:+-$RLZ}.$COMP"
echo $INITRDNAME
./salt/extra/create-initextra.sh $COMP $DEBUG
mv salt/extra/initextra.$COMP "$startdir"/$INITRDNAME
cd "$startdir"
md5sum "$INITRDNAME" > "$INITRDNAME.md5"
